#!/usr/bin/env bash
# ---------------------------------------------------------------
# Rebuild the Unity game as a WebGL player (headless) and stage it
# into public/game/ so the site can run it in the browser.
#
# Usage:
#   npm run build:webgl
#
# Runs Unity in batch mode against the sibling "Yum Jump" project,
# calling BuildScript.BuildWebGL (Assets/Editor/BuildScript.cs), which
# writes Builds-WebGL/ (index.html, Build/, TemplateData/) from the
# enabled Build Settings scenes. The output is then copied verbatim
# into public/game/, which Vite copies into dist/ on `npm run build`.
# So the normal `npm run deploy` uploads it with no extra steps.
#
# REQUIREMENTS:
#   * The "WebGL Build Support" module must be installed for this Unity
#     version (Unity Hub > 6000.0.51f1 > Add Modules). Without it the
#     build fails immediately.
#   * In the Unity project: Player Settings > WebGL > Publishing Settings,
#     set Compression Format = Disabled (or Gzip + Decompression Fallback).
#     Otherwise Unity emits .br/.gz assets that need special Apache
#     Content-Encoding headers the shared host does not provide.
#
# Overrides:
#   UNITY_EXE=/path/to/Unity.exe       (default: Hub 6000.0.51f1)
#   GAME_PROJECT_DIR="../Yum Jump"     (Unity project root)
# ---------------------------------------------------------------

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

GAME_PROJECT_DIR="${GAME_PROJECT_DIR:-../Yum Jump}"
UNITY_EXE="${UNITY_EXE:-/c/Program Files/Unity/Hub/Editor/6000.0.51f1/Editor/Unity.exe}"

# Folder the site serves the WebGL player from: https://site/game/index.html
WEBGL_OUT="public/game"

if [[ ! -d "$GAME_PROJECT_DIR" ]]; then
  echo "error: Unity project not found: $GAME_PROJECT_DIR" >&2
  exit 1
fi
if [[ ! -x "$UNITY_EXE" && ! -f "$UNITY_EXE" ]]; then
  echo "error: Unity editor not found at: $UNITY_EXE" >&2
  echo "       set UNITY_EXE to your 6000.0.51f1 Unity.exe." >&2
  exit 1
fi

# Windows-style absolute project path (Unity doesn't grok MSYS paths).
PROJECT_WIN="$(cd "$GAME_PROJECT_DIR" && pwd -W)"
BUILD_OUT="${GAME_PROJECT_DIR}/Builds-WebGL"
LOG_FILE="${GAME_PROJECT_DIR}/Logs/build-webgl.log"

# Refuse to build if the editor already has the project open: a second
# Unity instance on the same project fails partway and is confusing.
if [[ -f "${GAME_PROJECT_DIR}/Temp/UnityLockfile" ]]; then
  echo "error: the Unity Editor appears to have this project open." >&2
  echo "       Close it (or the build will fail), then re-run." >&2
  exit 1
fi

echo "==> Unity:   $UNITY_EXE"
echo "==> project: $PROJECT_WIN"
echo "==> cleaning Builds-WebGL/ for a fresh output"
rm -rf "$BUILD_OUT"

echo "==> building WebGL (headless; this can take several minutes)..."
set +e
"$UNITY_EXE" \
  -batchmode \
  -quit \
  -projectPath "$PROJECT_WIN" \
  -executeMethod BuildScript.BuildWebGL \
  -logFile "$(cd "$GAME_PROJECT_DIR" && pwd -W)/Logs/build-webgl.log"
UNITY_RC=$?
set -e

if [[ $UNITY_RC -ne 0 || ! -f "${BUILD_OUT}/index.html" ]]; then
  echo "error: Unity WebGL build failed (exit $UNITY_RC). Last 40 log lines:" >&2
  [[ -f "$LOG_FILE" ]] && tail -n 40 "$LOG_FILE" >&2
  exit 1
fi

echo "==> staging WebGL player -> ${WEBGL_OUT}"
rm -rf "$WEBGL_OUT"
mkdir -p "$WEBGL_OUT"
# Copy the build contents (not the folder itself) into public/game/.
cp -r "${BUILD_OUT}/." "$WEBGL_OUT/"

# The site-wide .htaccess caches .js/.wasm as immutable for a year, but
# Unity reuses the same build filenames every time -- so without this a
# returning visitor would keep playing a stale, cached build. This nested
# .htaccess overrides caching for just the game files (Apache applies the
# closest .htaccess), so each deploy is picked up while still allowing a
# short cache to avoid re-downloading on every click.
cat > "${WEBGL_OUT}/.htaccess" <<'HTACCESS'
# Auto-generated by scripts/build-webgl.sh -- do not edit by hand.
# Unity WebGL build files reuse the same names across builds, so they must
# NOT be cached immutably (the site-wide rule would otherwise pin a stale
# build). Revalidate frequently so new deploys are served promptly.
<IfModule mod_headers.c>
  <FilesMatch "\.(js|wasm|data|symbols\.json|framework\.js)$">
    Header set Cache-Control "public, max-age=300, must-revalidate"
  </FilesMatch>
</IfModule>
<IfModule mod_mime.c>
  AddType application/wasm .wasm
</IfModule>
HTACCESS

echo "==> done: ${WEBGL_OUT}/index.html"
echo "    $(date -r "${BUILD_OUT}/index.html" '+built %Y-%m-%d %H:%M:%S')"
echo "    It will be deployed by 'npm run deploy' (Vite copies public/ -> dist/)."
